name: standard-pipeline
on:
  push:
      branches:
        - CI-testing-2
  pull_request:
    branches:
      - CI-testing-2
jobs:
  dowwnload-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: 'echo "::debug::Set the Octocat variable"'
      - run: npm install jest --save
      - run: jest - v 
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
  